### ISSUE TITLE
Add pipe operator 

### ISSUE THREAD

**Issue by arzzen** [arzzen/pert#1]
It would be incredibly useful to be able to pass contents to pert command.

example:
pert.sh | cat times.txt
pert.sh | echo "1,2,3 4,5,6"

**Comment by pv2k** [comment]
i would love to work on this one

**Comment by arzzen** [comment]
It will be nice @pv2k

**Comment by pv2k** [comment]
thank you @arzzen, can i post my doubts here on comments section??? or do you have a  slack account???

**Comment by arzzen** [comment]
@pv2k add your doubts here, thanks

**Comment by pv2k** [comment]
@arzzen not good at bash. I just know basics of it. Can you tell me how can i do this??? I mean any resources or links needed to understand and code it.

**Comment by arzzen** [comment]
e.g. http://ryanstutorials.net/linuxtutorial/piping.php 
https://www.gnu.org/software/bash/manual/html_node/Pipelines.html

**Comment by pv2k** [comment]
Wouldn't the example above be like 
cat times.txt | pert.sh  and
echo "1,2,3 4,5,6" | pert.sh.
This is because we are sending the output of the command as an input to the pert,
Am I right??? @arzzen

**Comment by arzzen** [comment]
@pv2k yes you´re right.

**Comment by pv2k** [comment]
Okay :smiley:

**Comment by pv2k** [comment]
#2 PR piping included

**Comment by pv2k** [comment]
#6  PR piping included and conflicts resolved.
